### ISSUE TITLE
Add ability for admins to suspend accounts

### ISSUE THREAD

**Issue by c-w** [OPWEN/opwen-webapp#3]
From @nzola:

> Barb, who is planning to deploy Lokole in Uganda suggested to give the localadmin of lokole some power allow or block users in case of system abuse.
> They wanted a admin special logging to control their particular Lokole network for sustainable revenue. This way if the user does not pay, he cannot logging, like school network admin or Internet café.

**Comment by nzola** [comment]
Thanks for implementing the admin acct option!

- Nzola
